services:
  - type: web
    name: blood-bank-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FRONTEND_ORIGIN
        value: https://blood-banking-using-cloud-9kjc.vercel.app
      - key: DATABASE_URL
        value: postgresql://postgres.zvgctanqubivayfjqfec:Aakarsh%40123@aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
      - key: JWT_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        value: re_YmoVdgrC_3gyEb5T1TAgdrLr5Ai3eeHYv
      - key: SMTP_USER
        value: ""
      - key: SMTP_PASS
        value: ""
